app = "transactional-supabase-foobar"
primary_region = "ord"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  # Uses the Dockerfile in your project root
  # Fly will automatically detect and use your Dockerfile

[deploy]
  strategy = "rolling"
  
[env]
  NODE_ENV = "production"
  PORT = "8082"

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"  # You may need to add this endpoint to your Fastify server

[vm]
  size = "shared-cpu-1x"
  memory = "1gb"