packages:
  - "odw/apps/*"
  - "odw/services/*"
  - "odw/packages/*"
  - "ufa/apps/*"
  - "ufa/services/*"
  - "ufa/packages/*"

catalog:
  # TypeScript and Development Tools
  typescript: "^5.8.3"
  eslint: "^8.57.1"
  prettier: "^3.6.2"
  
  # Type Definitions
  "@types/node": "^20.12.12"
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.0"
  
  # React Ecosystem
  react: "^19.1.0"
  react-dom: "^19.1.0"
  
  # Tanstack Libraries
  "@tanstack/react-query": "^5.81.2"
  "@tanstack/react-query-devtools": "^5.81.2"
  "@tanstack/react-router": "^1.121.41"
  "@tanstack/router-devtools": "^1.121.41"
  "@tanstack/react-table": "^8.21.3"
  "@tanstack/react-form": "^1.12.3"
  "@tanstack/router-plugin": "^1.121.41"
  
  # UI Libraries
  tailwindcss: "^4.1.10"
  "@tailwindcss/vite": "^4.1.10"
  "@tailwindcss/cli": "^4.1.10"
  "@tailwindcss/postcss": "^4.1.10"
  lucide-react: "^0.522.0"
  clsx: "^2.1.1"
  class-variance-authority: "^0.7.1"
  tailwind-merge: "^3.3.1"
  tailwindcss-animate: "^1.0.7"
  
  # Backend Frameworks
  fastify: "^5.4.0"
  "@fastify/cors": "^10.0.1"
  "@fastify/swagger": "^9.5.1"
  "@fastify/swagger-ui": "^5.2.3"
  
  # Data Validation and ORM
  zod: "^3.25.76"
  drizzle-orm: "^0.29.1"
  drizzle-zod: "^0.5.1"
  drizzle-kit: "^0.20.7"
  
  # AI SDKs
  ai: "5.0.0-beta.28"
  "@ai-sdk/react": "2.0.0-beta.28"
  "@ai-sdk/anthropic": "2.0.0-beta.10"
  "@ai-sdk/openai": "2.0.0-beta.12"
  
  # Moose Framework
  "@514labs/moose-lib": "latest"
  "@514labs/moose-cli": "latest"
  
  # Database and Realtime
  "@supabase/supabase-js": "^2.39.1"
  "@supabase/realtime-js": "^2.10.2"
  "@elastic/elasticsearch": "^8.15.0"
  pg: "^8.11.3"
  
  # Other Common Dependencies
  axios: "^1.7.7"
  dotenv: "^16.3.1"
  tsx: "^4.7.0"
  autoprefixer: "^10.4.21"
  vite: "^5.2.0"
  "@vitejs/plugin-react": "^4.3.3"
  
  # Date and Time
  date-fns: "^4.1.0"
  
  # UI Components
  sonner: "^2.0.6"
  recharts: "^3.0.2"
  react-hook-form: "^7.60.0"
  "@hookform/resolvers": "^5.1.1"
  
catalogs:
  # Development tools with specific versions for certain projects
  dev-tools:
    typescript: "5.5.4"
    "@types/node": "^24.0.3"
  
  dev-tools-v5-3:
    typescript: "^5.3.3"
    "@types/node": "^20.0.0"
    
  # Radix UI Components - used primarily in UI package
  radix-ui:
    "@radix-ui/react-accordion": "^1.2.11"
    "@radix-ui/react-alert-dialog": "^1.1.14"
    "@radix-ui/react-aspect-ratio": "^1.1.7"
    "@radix-ui/react-avatar": "^1.1.10"
    "@radix-ui/react-checkbox": "^1.3.2"
    "@radix-ui/react-collapsible": "^1.1.11"
    "@radix-ui/react-context-menu": "^2.2.15"
    "@radix-ui/react-dialog": "^1.1.14"
    "@radix-ui/react-dropdown-menu": "^2.1.15"
    "@radix-ui/react-hover-card": "^1.1.14"
    "@radix-ui/react-label": "^2.1.7"
    "@radix-ui/react-menubar": "^1.1.15"
    "@radix-ui/react-navigation-menu": "^1.2.13"
    "@radix-ui/react-popover": "^1.1.14"
    "@radix-ui/react-progress": "^1.1.7"
    "@radix-ui/react-radio-group": "^1.3.7"
    "@radix-ui/react-scroll-area": "^1.2.9"
    "@radix-ui/react-select": "^2.2.5"
    "@radix-ui/react-separator": "^1.1.7"
    "@radix-ui/react-slider": "^1.3.5"
    "@radix-ui/react-slot": "^1.2.3"
    "@radix-ui/react-switch": "^1.2.5"
    "@radix-ui/react-tabs": "^1.1.12"
    "@radix-ui/react-toggle": "^1.1.9"
    "@radix-ui/react-toggle-group": "^1.1.10"
    "@radix-ui/react-tooltip": "^1.2.7"
    
  # DnD Kit - used in UI and web-frontend-foobar
  dnd-kit:
    "@dnd-kit/core": "^6.3.1"
    "@dnd-kit/modifiers": "^9.0.0"
    "@dnd-kit/sortable": "^10.0.0"
    "@dnd-kit/utilities": "^3.2.2"
    
  # ESLint and TypeScript ESLint
  eslint-deps:
    "@eslint/js": "^9.30.0"
    "@typescript-eslint/eslint-plugin": "^8.0.0"
    "@typescript-eslint/parser": "^8.0.0"
    eslint-config-prettier: "^9.1.0"
    globals: "^15.0.0"
    
  # Additional UI Dependencies
  ui-extras:
    "@tabler/icons-react": "^3.34.0"
    cmdk: "^1.1.1"
    "embla-carousel-react": "^8.6.0"
    "input-otp": "^1.4.2"
    "next-themes": "^0.4.6"
    "react-day-picker": "^9.8.0"
    "react-resizable-panels": "^3.0.3"
    vaul: "^1.1.2"
    "react-number-format": "^5.4.4"
    "tw-animate-css": "^1.3.4"
    
  # Patch and Transform Libraries  
  transform-libs:
    "ts-patch": "^3.3.0"
    typia: "^7.6.0"
    
  # Logging and Utilities
  utils:
    "pino-pretty": "^13.0.0"
    ws: "^8.18.0"
    "@types/pg": "^8.10.9"
    "@types/ws": "^8.5.10"
    supabase: "^2.31.8"
