app = "retrieval-elasticsearch-foobar"
primary_region = "ord"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"
  
[env]
  NODE_ENV = "production"
  PORT = "8083"
  SKIP_ES_WAIT = "true"

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 2
  
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[vm]
  size = "shared-cpu-1x"
  memory = "1gb"