[theme]
base = "light"
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans-serif"

[server]
port = 8501
showEmailPrompt = false
headless = true
runOnSave = false
maxUploadSize = 200
# Keep default CORS and XSRF settings for security
enableStaticServing = true

[client]
showErrorDetails = "full"
# Allow navigation while hiding deploy buttons
toolbarMode = "minimal"

[runner]
magicEnabled = true
fastReruns = true

[browser]
gatherUsageStats = false  # Disable telemetry

[logger]
# Set logging level to reduce verbosity (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "ERROR"
# Custom message format for cleaner logs
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"
