services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
    deploy:
      resources:
        limits:
          memory: 4.5G
          cpus: '1.5'
        reservations:
          memory: 2G
          cpus: '0.75'

  # Kafka Connect - waits for analytical-base network to be created
  connect:
    image: quay.io/debezium/connect:3.0
    platform: linux/amd64
    ports:
     - 8084:8083
    environment:
     - BOOTSTRAP_SERVERS=redpanda:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
     - sqlserver
    networks:
     - default
     - analytical-sqlserver-moose-foobar_default
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.75'
        reservations:
          memory: 768M
          cpus: '0.35'

networks:
  analytical-sqlserver-moose-foobar_default:
    external: true
