name: Supabase Database Migration Pipeline

on:
  push:
    paths:
      - "ufa/services/transactional-supabase-foobar/database/supabase/migrations/**"
      - "ufa/services/transactional-supabase-foobar/src/database/schema.ts"
      - ".github/workflows/supabase-migration.yml"
  pull_request:
    paths:
      - "ufa/services/transactional-supabase-foobar/database/supabase/migrations/**"
      - "ufa/services/transactional-supabase-foobar/src/database/schema.ts"

jobs:
  validate-migrations:
    name: Validate Database Migrations
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ufa/services/transactional-supabase-foobar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Lint migration files
        run: |
          echo "🔍 Linting migration files..."
          supabase db lint --workdir database/supabase --project-ref "$PROJECT_REF"
        env:
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Validate migrations (dry run)
        run: |
          echo "🧪 Testing migrations against production database (dry run)..."
          cd database/supabase
          supabase db push --db-url "$DATABASE_URL" --dry-run --project-ref "$PROJECT_REF"
          echo "✅ Migration validation successful - ready for deployment"
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL_PRODUCTION }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Check for schema drift
        run: |
          echo "🔄 Checking for schema drift..."
          cd database/supabase
          supabase db diff --db-url "$DATABASE_URL" --project-ref "$PROJECT_REF" > drift-check.sql || true
          if [ -s drift-check.sql ]; then
            echo "⚠️  Schema drift detected:"
            cat drift-check.sql
            echo ""
            echo "Please review the differences above to ensure migrations are complete."
          else
            echo "✅ No schema drift detected"
          fi
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL_PRODUCTION }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  deploy-migrations:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: validate-migrations
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ufa/services/transactional-supabase-foobar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy migrations to production
        run: |
          echo "🚀 Deploying migrations to production database..."
          cd database/supabase
          supabase db push --db-url "$DATABASE_URL" --project-ref "$PROJECT_REF"
          echo "✅ Migrations successfully deployed to production!"
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL_PRODUCTION }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
